### ISSUE TITLE
Selam

### ISSUE THREAD

**Issue by Turakine** [MustafaBKLZ/mustafabukulmez_com_dersler#1]
AnaForm.cs içerisinde ki kodlarda "using DevExpress.XtraEditors;" ve diğer kodlarda sürekli DevExpress var. Ben VisualStudio'yu sade kullanıyorum o nedenle bu yayımlananların sade halini gerçekten denemek isterim.
Emeğinize sağlık bu arada....

**Comment by MustafaBKLZ** [comment]
Selamlar,
Yorumunuz için teşekkürler...
Bence hemen DevExpress kurun ve kodlamanın tadını çıkartın. Böyle yapmamın sebebi devexpress kullanmaya teşvik etmek aslında. Gerek görsellik olarak gerekse kod yazmak olarak çok kolaylık sağlıyor.
Şiddetle tavsiye ederim.

Tavsiyenizi dikkate alıp windows nesnelerine dönüştürdüm. Şuanda projede DevExpress nesnesi bulunmuyor
